# pyproject.toml

[tool.ruff]
# Assume Python 3.10 based on Dockerfile
target-version = "py310"

[tool.ruff.lint]
# Enable Pyflakes (F), Pycodestyle Error (E), and Pycodestyle Warning (W) rules by default.
# E and W cover PEP 8 recommendations.
select = ["E", "W", "F"]

# Optionally, ignore specific rules if needed
# ignore = ["E501"]  # Example: ignore line length errors

# Exclude common directories
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.format]
# Enable formatting. You can add specific format settings here if needed.
# preview = true # Enable preview features if desired
# docstring-code-format = true # Format code in docstrings 
